language: ruby

# ruby version manager
rvm:
- 2.2.2

# install gems
install: gem install bundler

# run build on container-based infrastructure
sudo: false

before_script:
  # make scripts executable
  - bundle install
  - chmod +x ./script/cibuild

script:
  - ./script/cibuild

env:
  global:
    # dramatically speed up installation of html-proofer!
    # If not set a load of libraries must be compiled first.
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

notifications:
  slack: mlr-org:YQnzHKpngcveRUZgGJmm2eXB#buildnotifications
